# ?? ?? ??
server:
  port: 8080

# database ?? ??
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-uni.cniokc8sqj9u.ap-southeast-2.rds.amazonaws.com/university?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 12345678
  thymeleaf:
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB
        location: C:/springboot_img/images/
    cache: false
    mail:
      host: smtp.gmail.com
      port: 587
      username: dlwdjwnj1114@gmail.com
      password: your-email-password
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
play-ground:
  local-test: test


jwt:
  secret: 847c7696811c1277de7cf2074712c4ee72b1cba9eb2560ee6b16b47abe5d1212

