spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/game?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    ddl-auto: update
