name: HoeStory Github Action
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions: write-all
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'game'
          mysql user: 'user'
          mysql password: '1234'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
 
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Test with Gradle
        run: ./gradlew test
